version: '3.7'

services:
  minio:
    image: minio/minio:latest
    # for DNS resolve
    restart: always
    ports:
      - 9000:9000
      - 9090:9090 # web
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9090" /data
    networks:
      clevernet.test:

  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: USERNAME
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    volumes:
      - mongo_data:/data/db
    networks:
      clevernet.test:

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      clevernet.test:

  # docker compose stop backend && docker compose up --build backend
  backend:
    image: windowskonon1337/cleversearch_backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - mongodb
      - minio
    volumes:
      - minio_data:/app/minio_files
    networks:
      clevernet.test:

  mlcore:
    image: windowskonon1337/cleversearch_mlcore
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
      - mongodb
      - minio
    networks:
      clevernet.test:

  frontend:
    image: windowskonon1337/cleversearch_frontend
    ports:
      - 443:443
    restart: always
    volumes:
      - ./certs:/app/frontend/certs
    depends_on:
      - backend
    networks:
      clevernet.test:

volumes:
  minio_data:
  mongo_data:

networks:
  clevernet.test:
    driver: bridge
    # dd network inspect clevernet.test
    name: clevernet.test
