version: '3.7'

services:
  minio:
    image: minio/minio:latest
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090" # web
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9090" /data
    
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 1488:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "1338:5672"
      - "1337:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mlcore:
    image: cleversearch_mlcore
    restart: always

volumes:
  minio_data:
  mongo_data: