name: Docker Build and Publish

on:
  push:
    branches:
      - main
      - dev-RK2_CLEVER

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login --username windowskonon1337 --password-stdin

    - name: Build backend image
      run: docker build -t windowskonon1337/cleversearch_backend:latest ./backend

    - name: Push Docker image to Docker Hub
      run: docker push windowskonon1337/cleversearch_backend:latest