name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'dev*'

jobs:
  build_backend:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login --username windowskonon1337 --password-stdin
      - name: Build backend image
        run: docker build -t windowskonon1337/cleversearch_backend:latest ./backend
      - name: Push backend image to Docker Hub
        run: docker push windowskonon1337/cleversearch_backend:latest

  build_mlcore:
    name: Build and Push MLCore Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login --username windowskonon1337 --password-stdin
      - name: Build mlcore image
        run: docker build -t windowskonon1337/cleversearch_mlcore:latest ./MLCore
      - name: Push mlcore image to Docker Hub
        run: docker push windowskonon1337/cleversearch_mlcore:latest

  build_frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login --username windowskonon1337 --password-stdin
      - name: Build frontend image
        run: docker build -t windowskonon1337/cleversearch_frontend:latest ./frontend
      - name: Push frontend image to Docker Hub
        run: docker push windowskonon1337/cleversearch_frontend:latest

  deploy:
    name: Deploy on Server
    needs: [build_backend, build_mlcore, build_frontend]
    # needs: [build_backend, build_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Update Docker Compose on Production
        uses: appleboy/scp-action@master
        with:
          host: 89.208.208.128
          username: ubuntu
          key: ${{ secrets.SSH_SERVER_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/clever/docker-compose.yml"
      - name: SSH and Restart Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 89.208.208.128
          username: ubuntu
          key: ${{ secrets.SSH_SERVER_KEY }}
          script: |
            cd ~/clever
            docker compose down
            docker compose pull
            docker compose up -d
